#!/usr/bin/env bash
# This script displays a string 10 times using a while loop
# On the 9th iteration it displays another
# with An if statement must be used

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 9 ]
	then
		echo "Hi"
	fi

	echo "Best School"
	(( counter++))
done
