#!/usr/bin/env bash
# This script loops from 1 t 10
# Displays the first str for the 4th loop iteration
# Displays the 2nd for the 8th loop iteration
# Displays the 3rd for the other iterations
# Must use while loop, if, elif and else statements

counter=0

while [ $counter -lt 10 ]
do
	if [ $counter -eq 3 ]
	then
		echo "bad luck"
	elif [ $counter -eq 7 ]
	then
		echo "good luck"
	else
		echo "Best School"
	fi
	(( counter++ ))
done
